version: '3'
services:
  #само приложение
  web:
    build:
      context: .
      dockerfile: Dockerfile # Определяет, как собирать образ для Django из Dockerfile.
    ports:
      - "8000:8000"
    depends_on:
      - db # Указывает, что этот сервис зависит от сервиса "db".
      - redis   # Указывает, что этот сервис зависит от сервиса "redis".



# PostgreSQL сервис
  db:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready' ]
      interval: 10s
      timeout: 5s
      retries: 5


# Redis сервис
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
# Celery  сервис
  celery:
    restart: always
    build: .
    container_name: celery_app
    depends_on:
      - db
      - redis
    healthcheck:
      test: [ "CMD", "celery", "inspect", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
# Celery   beat сервис

networks:
  myNet:
    driver: bridge

